"""add all proposal section tables

Revision ID: f4ea06bc1db5
Revises: 880fbb3a622a
Create Date: 2026-02-27 14:46:56.217017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4ea06bc1db5'
down_revision: Union[str, None] = '880fbb3a622a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposed_people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('employee_name', sa.String(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=True),
    sa.Column('role_on_project', sa.String(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('cv_path', sa.String(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proposed_people_proposal_id'), 'proposed_people', ['proposal_id'], unique=False)
    op.create_table('scope_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scope_sections_proposal_id'), 'scope_sections', ['proposal_id'], unique=False)
    op.create_table('wbs_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('wbs_code', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wbs_items_proposal_id'), 'wbs_items', ['proposal_id'], unique=False)
    op.create_table('deliverables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('wbs_id', sa.UUID(), nullable=True),
    sa.Column('deliverable_ref', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('report', 'model', 'specification', 'drawing_package', 'other', name='deliverabletype'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('responsible_party', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('tbd', 'in_progress', 'complete', name='deliverablestatus'), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wbs_id'], ['wbs_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliverables_proposal_id'), 'deliverables', ['proposal_id'], unique=False)
    op.create_table('pricing_rows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('wbs_id', sa.UUID(), nullable=True),
    sa.Column('role_title', sa.String(), nullable=True),
    sa.Column('staff_name', sa.String(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hours_by_phase', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wbs_id'], ['wbs_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rows_proposal_id'), 'pricing_rows', ['proposal_id'], unique=False)
    op.create_table('schedule_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('wbs_id', sa.UUID(), nullable=True),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('responsible_party', sa.String(), nullable=True),
    sa.Column('is_milestone', sa.Boolean(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wbs_id'], ['wbs_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_items_proposal_id'), 'schedule_items', ['proposal_id'], unique=False)
    op.create_table('drawings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('wbs_id', sa.UUID(), nullable=True),
    sa.Column('deliverable_id', sa.UUID(), nullable=True),
    sa.Column('drawing_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=True),
    sa.Column('scale', sa.String(), nullable=True),
    sa.Column('format', sa.Enum('pdf', 'dwg', 'revit', 'other', name='drawingformat'), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('responsible_party', sa.String(), nullable=True),
    sa.Column('revision', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('tbd', 'in_progress', 'complete', name='drawingstatus'), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wbs_id'], ['wbs_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawings_proposal_id'), 'drawings', ['proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_drawings_proposal_id'), table_name='drawings')
    op.drop_table('drawings')
    op.drop_index(op.f('ix_schedule_items_proposal_id'), table_name='schedule_items')
    op.drop_table('schedule_items')
    op.drop_index(op.f('ix_pricing_rows_proposal_id'), table_name='pricing_rows')
    op.drop_table('pricing_rows')
    op.drop_index(op.f('ix_deliverables_proposal_id'), table_name='deliverables')
    op.drop_table('deliverables')
    op.drop_index(op.f('ix_wbs_items_proposal_id'), table_name='wbs_items')
    op.drop_table('wbs_items')
    op.drop_index(op.f('ix_scope_sections_proposal_id'), table_name='scope_sections')
    op.drop_table('scope_sections')
    op.drop_index(op.f('ix_proposed_people_proposal_id'), table_name='proposed_people')
    op.drop_table('proposed_people')
    # ### end Alembic commands ###
